#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

usage() {
    cat <<END_DOC
USAGE:

  bio bacterial-gc-content <species-name>

DESCRIPTION:

  Get mean GC-content of a bacterial species. Average over all the item
  found in the dataset. This might be roughly correct but gives a basic
  idea.

EXAMPLES:

    $ bacterial-gc-content Escherichia

OPTIONS:

  --help: Display this help message

AUTHOR:

  Samuel Barreto, (2017-05-29)

END_DOC

    exit 0
}

expr "$*" : ".*--help" > /dev/null && usage
if [ $# -eq 0 ]; then > /dev/null && usage; fi

readonly LOG_FILE="/tmp/$(basename "$0").log"
info()    { echo "INFO:  $@" | tee -a "$LOG_FILE" >&2 ; }
warn()    { echo "WARN:  $@" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "ERROR: $@" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "FATAL: $@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

cleanup() {
    rm "$LOG_FILE"
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    awk -F$'\t' "/$1/{total += \$10; count++ } END { print total/count }" \
        $BIO_SOURCE_DIR/data/2017-02-24_prokaryotes.tsv \
        2> "$LOG_FILE" || \
        error "Species not found.\n\tSpecies name are usually case sensitive."


fi
