#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

#' USAGE:
#'   bacterial-gc-content <species-name>
#' DESCRIPTION:
#'   Get GC-content of a bacterial species.
#' EXAMPLES:
#'    bacterial-gc-content Escherichia
#' OPTIONS:
#'   --help: Display this help message

usage() { grep "^#'" "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage
if [ $# -eq 0 ]; then > /dev/null && usage; fi

readonly LOG_FILE=$(mktemp -t $(basename "$0").log)
info()    { echo "[INFO]    $@" | tee -a "$LOG_FILE" >&2 ; }
warning() { echo "[WARNING] $@" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "[ERROR]   $@" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "[FATAL]   $@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

cleanup() {
    rm "$LOG_FILE"
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    trap cleanup EXIT

    awk -F$'\t' "/$1/{print \$10}" ~/these/gc-content/data/2017-02-24_prokaryotes.tsv
fi
