MUSCLE (3.8) multiple sequence alignment CLUSTAL

Altern_WeakStrong      AAGGTGGAAGAGAAGGAGGCCACGCATGGCTGTGCGTGTTGCACCCGGATTAATGCAGGT
Strong                 AAGGTGGAAGAGAAGGAGGCCACGCATGGCTGTGCGTGTTGCACCCGGATTAATGCAGGT
wt                     AAGGTGGAAGAGAAGGAGGCCACGCATGGCTGTGCGTGTTGCACCCGGATTAATGCAGTT
Weak                   AAGGTGGAAGAGAAGGAGGCCACGCATGGCTGTGCGTGTTGCACCCGGATTAATGCATTT
Altern_StrongWeak      AAGGTGGAAGAGAAGGAGGCCACGCATGGCTGTGCGTGTTGCACCCGGATTAATGCATTT
                       *********************************************************  *

Altern_WeakStrong      AAAGCGAATGTTCGGATAGACATGCTCATTGGCAAAAATTTTGCTCACTGCCTCAATGGC
Strong                 AAAGCGAATGTTCGGATAGACATGCTCACCGGCAAAAATTTTGCTCACTGCCTCAATGGC
wt                     AAAGCGAATGTTCGGATAGACATGCTCACTGGCAAAAATTTTGCTCACTGCCTCAATGGC
Weak                   AAAGCGAATGTTCGGATAGACATGCTCATTGGCAAAAATTTTGCTCACTGCCTCAATGGC
Altern_StrongWeak      AAAGCGAATGTTCGGATAGACATGCTCACCGGCAAAAATTTTGCTCACTGCCTCAATGGC
                       ****************************  ******************************

Altern_WeakStrong      CCCCTTGGACACCGAATATGCACCCCATAAAGCACGTGCTTCACGTCCTACACCAGAACG
Strong                 CCCCTTGGACACCGAATATGCACCCCATAGGGCACGTGCTTCACGTCCTACACCAGAACG
wt                     CACCTTGGACACCGAATATGCACCCCATAAGGCACGTGCTTCACGTCCTACACCAGAACT
Weak                   AACCTTGGACACCGAATATGCACCCCATAAAGCACGTGCTTCACGTCCTACACCAGAAAT
Altern_StrongWeak      AACCTTGGACACCGAATATGCACCCCATAGGGCACGTGCTTCACGTCCTACACCAGAAAT
                         ***************************  ***************************

Altern_WeakStrong      TGCAAATACAACCGAGGCATTATCTGACCTTTTAAGTAACGGTAGCAGCGCCTGAGTCCG
Strong                 TGCAAATACAACCGAGGCATTATCTGACCTTCCAAGTAACGGTAGCAGCGCCTGAGTCCG
wt                     TGCAAATACAACCGAGGCATTATCTGACCTTTCAAGTAACGGTAGCAGCGCCTGAGTCAG
Weak                   TGCAAATACAACCGAGGCATTATCTGACCTTTTAAGTAACGGTAGCAGCGCCTGAGTCAT
Altern_StrongWeak      TGCAAATACAACCGAGGCATTATCTGACCTTCCAAGTAACGGTAGCAGCGCCTGAGTCAT
                       *******************************  *************************

Altern_WeakStrong      CACAAAAGGCGCACGCAGGTTAACAGCCATTACATCATCCCAGACATCGGCTGGGTAAGG
Strong                 CACAAAAGGCGCACGCAGGTTAACAGCCACCACATCATCCCAGACATCGGCTGGGTAAGG
wt                     CACAAAAGGCGCACGCAGGTTAACAGCCATCACATCATCCCAGACATCGGCTGGGTAATG
Weak                   CACAAAAGGCGCACGCAGGTTAACAGCCATTACATCATCCCAGACATCGGCTGGGTAATT
Altern_StrongWeak      CACAAAAGGCGCACGCAGGTTAACAGCCACCACATCATCCCAGACATCGGCTGGGTAATT
                       *****************************  ***************************

Altern_WeakStrong      CGCTAGGGGCACACGTTCACCCAAGATACTTGCATTGTGCAAAATTCCGTCCAGACGCCC
Strong                 CGCTAGGGGCACACGTTCACCCAAGATACCCGCATTGTGCAAAATTCCGTCCAGACGCCC
wt                     CGCTAGGGGCACACGTTCACCCAAGATACCTGCATTGTGCAAAATTCCGTCCAGACGCCC
Weak                   CGCTAGGGGCACACGTTCACCCAAGATACTTGCATTGTGCAAAATTCCGTCCAGACGCCA
Altern_StrongWeak      CGCTAGGGGCACACGTTCACCCAAGATACCCGCATTGTGCAAAATTCCGTCCAGACGCCA
                       *****************************  ****************************

Altern_WeakStrong      CAACTGATCTTCCAGTGTATTGAAGAGCAACTCATAGTCACGGTCCGATGCACTGGAACG
Strong                 CAACTGATCTTCCAGTGTATTGAAGAGCGGCTCATAGTCACGGTCCGATGCACTGGAACG
wt                     AAACTGATCTTCCAGTGTATTGAAGAGCAGCTCATAGTCACGGTCCGATGCACTGGAAAG
Weak                   AAACTGATCTTCCAGTGTATTGAAGAGCAACTCATAGTCACGGTCCGATGCACTGGAAAT
Altern_StrongWeak      AAACTGATCTTCCAGTGTATTGAAGAGCGGCTCATAGTCACGGTCCGATGCACTGGAAAT
                        ***************************  ****************************

Altern_WeakStrong      CTGTAAAGGTAAGATCGCAGGCTGCGGTGTACCCAAGCTTTCGATTTCATCATAGATGAC
Strong                 CTGTAAAGGTAAGATCGCAGGCTGCGGTGCGCCCAAGCTTTCGATTTCATCATAGATGAC
wt                     CTGTAAAGGTAAGATCGCAGGCTGCGGTGCACCCAAGCTTTCGATTTCATCATAGATGAC
Weak                   CTGTAAAGGTAAGATCGCAGGCTGCGGTGTACCCAAGCTTTCGATTTCATCATAGATGAA
Altern_StrongWeak      CTGTAAAGGTAAGATCGCAGGCTGCGGTGCGCCCAAGCTTTCGATTTCATCATAGATGAA
                       *****************************  ****************************

Altern_WeakStrong      GTCAAGTTTATTTAAGGTTCTTCCATGCAAAACAACAGTCGCACCGTGTAGCGCATAGCT
Strong                 GTCAAGTTTATTTAAGGTTCTTCCATGCAGGACAACAGTCGCACCGTGTAGCGCATAGCT
wt                     TTCAAGTTTATTTAAGGTTCTTCCATGCAGAACAACAGTCGCACCGTGTAGCGCATAGCT
Weak                   TTCAAGTTTATTTAAGGTTCTTCCATGCAAAACAACAGTCGCACCGTGTAGCGCATAGCT
Altern_StrongWeak      TTCAAGTTTATTTAAGGTTCTTCCATGCAGGACAACAGTCGCACCGTGTAGCGCATAGCT
                        ****************************  *****************************

Altern_WeakStrong      CCTGGCTGCTGCTCGTCCAATTCCATCGCTTGCACCTGTAATTAAAATAATACGGCCTTT
Strong                 CCTGGCTGCTGCTCGTCCAATTCCATCGCCCGCACCTGTAATTAAAATAATACGGCCTTT
wt                     CATGGCTGCTGCTCGTCCAATTCCATCGCCTGCACCTGTAATTAAAATAATACGGCCTTT
Weak                   AATGGCTGCTGCTCGTCCAATTCCATCGCTTGCACCTGTAATTAAAATAATACGGCCTTT
Altern_StrongWeak      AATGGCTGCTGCTCGTCCAATTCCATCGCCCGCACCTGTAATTAAAATAATACGGCCTTT
                         ***************************  *****************************

Altern_WeakStrong      TAATAAGGCGGTACGAGGTTGATATTCTAAATATTTCATTGGAAAACCTCCTTTAAAAGC
Strong                 TAATAAGGCGGTACGAGGTTGATATTCTGGATATTTCATTGGAAAACCTCCTTTAAAAGC
wt                     TAATAAGTCGGTACGAGGTTGATATTCTGAATATTTCATTGGAAAACCTCCTTTAAAATC
Weak                   TAATAATTCGGTACGAGGTTGATATTCTAAATATTTCATTGGAAAACCTCCTTTAAAATA
Altern_StrongWeak      TAATAATTCGGTACGAGGTTGATATTCTGGATATTTCATTGGAAAACCTCCTTTAAAATA
                       ******  ********************  ****************************

Altern_WeakStrong      GAGTCATTATTATGATGTTTGTAGCATAATATCCTGATTTAATGGCGTAATGTGTAGC-T
Strong                 GAGTCATTATTATGATGTTTGTAGCATGGTATCCTGATTTAATGGCGTAATGTGTAGC-T
wt                     GAGTCATTATTATGATGTTTGTAGCATAGTATCCTGATTTAATGGCGTAATGTGTAGC-T
Weak                   GAGTCATTATTATGATGTTTGTAGCATAATATCCTGATTTAATGGCGTAATGTGTAGC-T
Altern_StrongWeak      GAGTCATTATTATGATGTTTGTAGCATGGTATCCTGATTTAATGGCGTAATGTGTAGCTT
                       ***************************  ***************************** *

Altern_WeakStrong      GTGGAGACAAAATTTTCTGTAACTCGGTAACATGCCTCTTTGCTTTCCTCCTCGC
Strong                 GT-GAGACAAAATTTTCTGTAACTCGGTAACATGCCTCTTTGCTTTCCTCCTCGC
wt                     GT-GAGACAAAATTTTCTGTAACTCGGTAACATGCCTCTTTGCTTTCCTCCTCGC
Weak                   GT-GAGACAAAATTTTCTGTAACTCGGTAACATGCCTCTTTGCTTTCCTCCTCGC
Altern_StrongWeak      GT-GAGACAAAATTTTCTGTAACTCGGTAACATGCCTCTTTGCTTTCCTCCTCGC
                       ** ****************************************************
